Done /api/articles with comments
Mohamedddm/BE-Solo-News pull request #7
Opened 2022-10-13 13:23 UTC by Mohamedddm

Can I jump on a call with whoever checks this, I have a couple of questions regarding layout n some tests

2022-10-13 14:03 UTC, itsaliabdallah requested changes
Please re submit once changes are made we discussed.

Thank youu

2022-10-14 15:49 UTC, elijaharley approved these changes
Please see comments and then good to merge and delete this branch

2022-10-14 15:49 UTC, elijaharley commented on __tests__/app.test.js
> +  });
These should be checked for contents using objectContaining rather than object.Keys to check the length as the keys could be different

2022-10-14 15:49 UTC, elijaharley commented on controller/article.controller.js
> +};
Don't forget to remove console.logs after using them

2022-10-14 15:49 UTC, elijaharley commented on model/article.model.js
> +};
Nice use of queryString here

2022-10-16 14:45 UTC, merged